name: FarLandsAgain
main: com.minefit.XerxesTireIron.FarLandsAgain.FarLandsAgain
version: 1.3.4
author: XerxesTireIron
description: Fixes noise generator so that Far Lands generate again :D
load: startup