name: FarLandsAgain
main: com.minefit.xerxestireiron.farlandsagain.FarLandsAgain
version: 2.4.2
author: XerxesTireIron
description: Fixes noise generator so that Far Lands generate again :D
load: startup
api-version: 1.13