name: FarLandsAgain
main: com.minefit.xerxestireiron.farlandsagain.FarLandsAgain
version: 1.5
author: XerxesTireIron
description: Fixes noise generator so that Far Lands generate again :D
load: startup